framework:
    messenger:
        routing:
            'Webgriffe\SyliusActiveCampaignPlugin\Message\Contact\ContactCreate': main
            'Webgriffe\SyliusActiveCampaignPlugin\Message\Contact\ContactUpdate': main
            'Webgriffe\SyliusActiveCampaignPlugin\Message\Contact\ContactRemove': main
            'Webgriffe\SyliusActiveCampaignPlugin\Message\Contact\ContactTagsAdder': main
            'Webgriffe\SyliusActiveCampaignPlugin\Message\Contact\ContactListsSubscriber': main
            'Webgriffe\SyliusActiveCampaignPlugin\Message\Contact\ContactListsUpdater': main
            'Webgriffe\SyliusActiveCampaignPlugin\Message\Contact\ContactAutomationEvent': main

            'Webgriffe\SyliusActiveCampaignPlugin\Message\Connection\ConnectionCreate': main
            'Webgriffe\SyliusActiveCampaignPlugin\Message\Connection\ConnectionUpdate': main
            'Webgriffe\SyliusActiveCampaignPlugin\Message\Connection\ConnectionRemove': main

            'Webgriffe\SyliusActiveCampaignPlugin\Message\EcommerceCustomer\EcommerceCustomerCreate': main
            'Webgriffe\SyliusActiveCampaignPlugin\Message\EcommerceCustomer\EcommerceCustomerUpdate': main
            'Webgriffe\SyliusActiveCampaignPlugin\Message\EcommerceCustomer\EcommerceCustomerRemove': main

            'Webgriffe\SyliusActiveCampaignPlugin\Message\EcommerceOrder\EcommerceOrderCreate': main
            'Webgriffe\SyliusActiveCampaignPlugin\Message\EcommerceOrder\EcommerceOrderUpdate': main
            'Webgriffe\SyliusActiveCampaignPlugin\Message\EcommerceOrder\EcommerceOrderRemove': main

            'Webgriffe\SyliusActiveCampaignPlugin\Message\Webhook\WebhookCreate': main

        buses:
            webgriffe_sylius_active_campaign_plugin.command_bus:
                middleware:
                    - validation

                    - doctrine_ping_connection

                    - doctrine_close_connection

                    - doctrine_transaction

                    - doctrine_open_transaction_logger

sylius_ui:
    events:
        sylius.admin.channel.update.form:
            blocks:
                active_campaign_form: '@WebgriffeSyliusActiveCampaignPlugin/Admin/Channel/_form.html.twig'
        sylius.admin.channel.create.form:
            blocks:
                active_campaign_form: '@WebgriffeSyliusActiveCampaignPlugin/Admin/Channel/_form.html.twig'
        sylius.shop.layout.javascripts:
            blocks:
                active_campaign_tracking: '@WebgriffeSyliusActiveCampaignPlugin/Shop/_active_campaign_tracking.html.twig'
twig:
    globals:
        webgriffe_active_campaign_tracking_account_id: '%env(default::WEBGRIFFE_SYLIUS_ACTIVE_CAMPAIGN_ACCOUNT_ID)%'
